image: ubuntu:18.04

stages:
    - test
    
test:
    stage: test
    script:
    - apt-get update -y
    - apt-get install -y python3-pip python-dev
    - pip3 install Flask
    - pip3 install requests
    - pip3 install gunicorn
    - pip3 install mysql-connector-python
    - pip3 install beautifulsoup4
    - cd advert
    - python3 tests.py
    - cd ..
    - cd indexer
    - python3 tests.py
    - cd ..
    - cd search
    - python3 tests.py